--- 
version: '2.1'

services:
   pd1:
     image: pingcap/pd:latest
     ports: 
       - "2379:2379"
       - "2380:2380"
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /data:/data
     command:
       - --name=pd1
       - --data-dir=/data/pd1
       - --client-urls=http://0.0.0.0:2379
       - --advertise-client-urls=http://pd1:2379
       - --peer-urls=http://0.0.0.0:2380
       - --advertise-peer-urls=http://pd1:2380
       - --initial-cluster=pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380
     restart: on-failure
   
   
   
    
