- name: cron backup conf
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    job: "{{ item.job }}"
  with_items:
    - { name: 'rsync_backup', minute: '00', hour: '00', job: '/bin/sh /server/scripts/rsync.backup.sh >/dev/null 2>&1' }
    - { name: 'backup_check', minute: '01', hour: '00', job: '/bin/sh /server/scripts/rsync.backup.check.sh >/dev/null 2>&1' }