- name: 101-intall zabbix yum
  yum:
    name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: present

- name: 102-conf yum source
  template:
    src: zabbix_repo.j2
    dest: /etc/yum.repos.d/zabbix.repo

- name: 103-install zabbix-agent
  yum: name=zabbix-agent state=installed

- name: 104-copy zabbix conf file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'zabbix_agentd.conf', dest: '/etc/zabbix/' }
    - { src: 'userparameter_tcp_state.conf', dest: '/etc/zabbix/zabbix_agentd.d/' }
  notify: restart zabbix-agent

- name: 105-boot zabbix-agent
  service: name=zabbix-agent state=started enabled=yes