- name: 101-intall zabbix yum
  yum:
    name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: present

- name: 102-conf yum source
  template:
    src: zabbix_repo.j2
    dest: /etc/yum.repos.d/zabbix.repo

- name: 102-install zabbinx and mariadb
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-agent
    - zabbix-get
    - mariadb
    - mariadb-server
    - MySQL-python
    - wqy-microhei-fonts
  notify:
    - remove_user
    - remove_test
    - set_password

- name: 103-boot mariadb.service
  service:
    name: mariadb.service
    state: started
    enabled: yes

- name: 104-copy conf file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'zabbix_server.conf.j2', dest: '/etc/zabbix/zabbix_server.conf' }
    - { src: 'zabbix_agentd.conf.j2', dest: '/etc/zabbix/zabbix_agentd.conf' }
    - { src: 'httpd_zabbix.conf.j2', dest: '/etc/httpd/conf.d/zabbix.conf' }
    - { src: 'my.cnf.j2', dest: '/etc/my.cnf' }
    - { src: 'mariadb.service.j2', dest: '/lib/systemd/system/mariadb.service' }
  notify: restart_zabbix

- name: 105-copy_sql
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'zabbix.sql', dest: '/server/scripts' }
    - { src: 'wqy-microhei.ttc', dest: '/usr/share/zabbix/assets/fonts/graphfont.ttf' }
    - { src: 'zabbix.conf.php', dest: '/etc/zabbix/web/' }
  notify: 
    - adddb_zabbix
    - create_user
    - import_sql

- name: 106-boot  zabbix-server
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - zabbix-server
    - zabbix-agent
    - httpd